### ISSUE TITLE
JSX parsing bugs

### ISSUE THREAD

**Issue by johnotander** [c8r/markdown#43]
### children props are overridden

```jsx
<Foo children='bar' />
```

Children prop is empty because the ast `children` attribute is used.

### unnecessary `p` tags

```jsx
<Foo>
  Bar
</Foo>
```

Results in

```html
<h1>
  <p>Bar</p>
</h1>
```

### complex jsx is borked

```jsx
<Foo>
  <Bar
    children={props.bar.map(b =>
      <Baz key={b}>{b}</Baz>
    )}
  />
</Foo>
```

Perhaps stuff like this is where we introduce the `.jsx` code block back?

### Expression based props error

```jsx
<Foo color={'pink'} />
```

Errors with (in next example):

```
Error
Error
    at tokens.reduce.type (http://localhost:3000/_next/-/page/index.js:2090:19)
    at Array.reduce (<anonymous>)
    at parse (http://localhost:3000/_next/-/page/index.js:2084:23)
    at Of.parser (http://localhost:3000/_next/-/page/index.js:823:18)
    at Of.tokenize [as tokenizeBlock] (http://localhost:3000/_next/-/page/index.js:72636:18)
    at Of.parse (http://localhost:3000/_next/-/page/index.js:68441:20)
    at Function.parse (http://localhost:3000/_next/-/page/index.js:80537:45)
    at pipelineParse (http://localhost:3000/_next/-/page/index.js:80284:16)
    at wrapped (http://localhost:3000/_next/-/page/index.js:80139:19)
    at next (http://localhost:3000/_next/-/page/index.js:80102:24)
```

**Comment by jxnblk** [comment]
Related, but seems like expression values in props aren't working for me – e.g. `<Box width={0.5} />`

**Comment by johnotander** [comment]
Confirmed and added to list.

**Comment by johnotander** [comment]
This list of bugs can be tracked by these new issues:

- fazouane-marouane/remark-jsx#16
- fazouane-marouane/remark-jsx#20
- fazouane-marouane/remark-jsx#19
